# -*- coding: utf-8 -*-
"""Travel planner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FG2GJdWYiCHIicrqiQputvxarax85KhT
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/travel planner/travel planner.xlsx"

import numpy as np
import pandas as pd

data=pd.read_excel(file_path)

data.head()

import pandas as pd

data = {
    "Distance_km": [100, 250, 500, 150],
    "Transport": ["Bus", "Car", "Flight", "Train"],
    "CO2_Emission": [10, 40, 150, 15]
}

df = pd.DataFrame(data)

best_option = df.loc[df["CO2_Emission"].idxmin()]

print("Eco-Friendly Travel Recommendation")
print("----------------------------------")
print("Transport:", best_option["Transport"])
print("Distance:", best_option["Distance_km"], "km")
print("CO2 Emission:", best_option["CO2_Emission"], "kg")